version: '3.4'

services:
  eureka-server:
    build:
      context: eserver
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  configserver:
    build:
      context: configserver
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      WAITFORIT_HOST: eureka-server
      WAITFORIT_PORT: 8761
      WAITFORIT_TIMEOUT: 30
    depends_on:
      - eureka-server

  postgres:
    image: postgres
    restart: always
    logging:
      driver: none
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: JavaLabs3
      PGPORT: 5432
    volumes:
      - /docker-volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  client:
    build:
      context: eclient
      dockerfile: Dockerfile
    ports:
      - "8081-8082:8081"
    environment:
      WAITFORIT_HOST: configserver
      WAITFORIT_PORT: 8888
      WAITFORIT_TIMEOUT: 60
    depends_on:
      - eureka-server
      - postgres
      - configserver

  gateway:
    build:
      context: apigateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      WAITFORIT_HOST: configserver
      WAITFORIT_PORT: 8888
      WAITFORIT_TIMEOUT: 60
    depends_on:
      - eureka-server
      - client
      - configserver

  rabbit:
    image: rabbitmq:3
    ports:
      - "15672:15672"
      - "5672:5672"